# Generated by Django 4.2.7 on 2023-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
