# Generated by Django 4.2.7 on 2023-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_client_id_client_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cpfCnpj',
            new_name='cpf_cnpj',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='publicPlace',
            new_name='public_place',
        ),
    ]
