# Generated by Django 4.2.7 on 2023-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
