# Generated by Django 4.2.7 on 2023-11-19 03:20

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_loadgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalCharges',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('potency', models.PositiveBigIntegerField()),
                ('potency_factor', models.PositiveBigIntegerField()),
                ('is_discharge_equipament', models.BooleanField(default=False)),
                ('active_power', models.PositiveBigIntegerField(editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.loadgroup')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
