# Generated by Django 4.2.7 on 2023-11-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_electricalcharges_active_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcharges',
            name='active_power',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
