# Generated by Django 4.2.7 on 2023-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_electricalcharges_active_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadgroup',
            name='is_discharge_group',
            field=models.BooleanField(default=False),
        ),
    ]
