# Generated by Django 4.2.7 on 2023-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_electricalcharges_apparent_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalcharges',
            name='power_factor',
            field=models.FloatField(),
        ),
    ]
