# Generated by Django 4.2.7 on 2023-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_electricalcharges_power_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalcharges',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='apparent_power',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='reactive_power',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
