# Generated by Django 4.2.7 on 2023-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_electricalcharges_active_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalcharges',
            name='final_factor_power',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='electricalcharges',
            name='total_apparent_power',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='electricalcharges',
            name='total_power',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='electricalcharges',
            name='total_reactive_power',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='active_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='apparent_power',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='electricalcharges',
            name='reactive_power',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
