# Generated by Django 4.2.7 on 2023-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_electricalcharges_final_factor_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalcharges',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
