# Generated by Django 4.2.7 on 2023-11-23 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_electricalcharges_active_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDescription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('circuit_number', models.PositiveBigIntegerField()),
                ('circuit_description', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project')),
            ],
        ),
    ]
