# Generated by Django 4.2.7 on 2023-11-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_loaddescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDescriptionByCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('electrical_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_description', to='api.electricalcharges')),
                ('load_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_description', to='api.loaddescription')),
            ],
        ),
        migrations.AddField(
            model_name='loaddescription',
            name='electrical_charges',
            field=models.ManyToManyField(related_name='electrical_charges', through='api.LoadDescriptionByCircuit', to='api.electricalcharges'),
        ),
    ]
