# Generated by Django 4.2.7 on 2023-11-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_loaddescriptionbycircuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddescriptionbycircuit',
            name='load_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_description', to='api.loaddescription'),
        ),
    ]
