# Generated by Django 4.2.7 on 2023-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_loaddescription_electrical_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddescription',
            name='electrical_charges',
            field=models.ManyToManyField(related_name='electrical', through='api.LoadDescriptionByCircuit', to='api.electricalcharges'),
        ),
    ]
