# Generated by Django 4.2.7 on 2023-11-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_loaddescriptionbycircuit_electrical_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddescriptionbycircuit',
            name='electrical_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.electricalcharges'),
        ),
        migrations.AlterField(
            model_name='loaddescriptionbycircuit',
            name='load_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical', to='api.loaddescription'),
        ),
    ]
